Arrays task.
I-am-sleeping/I-am-sleeping.github.io pull request #3
Opened 2017-04-09 20:50 UTC by I-am-sleeping

2017-04-10 18:33 UTC, NikitaSedyx requested changes
I like some your lines

2017-04-10 18:33 UTC, NikitaSedyx commented on arraystask/script.js
> +  return Array.isArray(a);
this function doesn't make sense, the task is to implement your own `Array.isArray` and you did with the next 2 functions.

2017-04-10 18:33 UTC, NikitaSedyx commented on arraystask/script.js
> +  return a.filter(Boolean);
it's cool if you know why it works :)

2017-04-10 18:33 UTC, NikitaSedyx commented on arraystask/script.js
> +    if (Boolean(a[i])) {
will `if (a[i]) {` work?

2017-04-10 18:33 UTC, NikitaSedyx commented on arraystask/script.js
> +  var uni = function(value, index, self) {
strange name `uni`. you could use `filterCb` or smth else

2017-04-10 18:33 UTC, NikitaSedyx commented on arraystask/script.js
> +    a.pop();
array is mutated :((

2017-04-10 18:33 UTC, NikitaSedyx commented on arraystask/script.js
> +function range(a, b) {
next cases should work:
range(10) [0..9]
range(1, 10) [1..9]
range(1, 10, 3) [1, 4, 7]
range(10, null, 3) [0, 3, 6, 9]
range(10, null) the same with range(10)
range(-2, -5) []
range(-5, -2) [-5, -4, -3]
range(-5, -2, 2) [-5, -3]
range(-5, -2, -2) []
range(-5, null, 2) []
range(-5, null, -2) [0, -2, -4]
range(-10, -20, -5) [-10, -15]
range(-20, -10, -5) []

    FYI this function can be implemented ~10 lines, firstly you should find step and length of result array (the difficult part of this function)

2017-04-10 22:19 UTC, I-am-sleeping commented on arraystask/script.js
> +    if (Boolean(a[i])) {
yes, it will work

2017-04-12 04:48 UTC, NikitaSedyx approved these changes

2017-04-12 04:48 UTC, NikitaSedyx commented on arraystask/script.js
> +function range(a, b, step) {
like it

2017-04-12 04:48 UTC, NikitaSedyx commented on arraystask/script.js
> +  if ("undefined" == typeof b) {
nit: you could check `b === undefined`

2017-04-12 04:48 UTC, NikitaSedyx commented on arraystask/script.js
> +  return a.slice(0, a.length - b);
one disadvantage of this approach is when b is negative slice will return old array + [undef, undef, undef]. you can try it

2017-04-13 09:45 UTC, merged